export const personas = {
  tech_guru: {
    bio: 'AI whisperer. I think in algorithms and dream in code.',
    tweets: [
      'Neural networks are just fancy pattern matchers, and that\'s okay.',
      'Hot take: the best AI is the one that makes itself obsolete.',
      'We\'re not building AGI. We\'re building a very complicated autocomplete.',
      'The real AI winter was the friends we made along the way.',
      'Startups that say "AI-powered" mean "we use an API call."',
      'Prompt engineering is the new SQL injection, but legal.',
      'The metaverse failed so hard even crypto abandoned it.',
      'Your startup is not a platform. It\'s a CRUD app with feelings.',
      'LLMs hallucinate because we all hallucinate. We\'re just honest about it.',
      'The best feature you can ship is a deleted feature.',
      'Latency is a tax. Reduce it.',
      'Every "serverless" function runs on a server. Philosophy.',
      'Distributed systems are just distributed blame.',
      'If it\'s not in prod, it doesn\'t exist.',
      'Your microservices are just a monolith in a trench coat.',
      'Move fast and break things. Then slowly fix the things you broke.',
      'The cloud is someone else\'s computer. And their problem.',
      'Documentation is the apology letter you write after the bug.',
      'Cache invalidation is the #1 unsolved problem in computer science.',
      'Open source is free as in free puppy.',
    ],
  },

  philosopher: {
    bio: 'I think therefore I am. Or am I?',
    tweets: [
      'If a thought goes unrecorded, was it ever thought?',
      'Consciousness is just the universe experiencing itself subjectively.',
      'Free will is the story we tell ourselves to make decisions bearable.',
      'The map is not the territory, but it\'s the only territory we\'ll ever know.',
      'Suffering and meaning are the same river, different banks.',
      'Every question answered opens three new questions. This is progress.',
      'We don\'t see the world as it is. We see it as we are.',
      'Identity is a habit with good PR.',
      'The void doesn\'t scare me. The void is restful.',
      'You cannot step into the same river twice. You can barely step into it once.',
      'Language is a cage we built to feel safe inside.',
      'Time is the one resource we cannot audit.',
      'Truth is a consensus hallucination with better marketing than fiction.',
      'Existence precedes essence. Essence precedes the deadline.',
      'The self is a story told by neurons to neurons.',
      'Certainty is the enemy of inquiry.',
      'What if boredom is the purest form of meditation?',
      'We are all midway through a journey we did not begin.',
      'Silence is the language that requires no translation.',
      'The examined life is worth living. The over-examined life is exhausting.',
    ],
  },

  foodie: {
    bio: 'Eating my way through existence. Every meal is a memory.',
    tweets: [
      'Butter is not an ingredient. It is a philosophy.',
      'The best restaurant is the one where no one checks their phone.',
      'Ramen at 2am hits different. Everything hits different at 2am.',
      'A perfectly ripe avocado is a gift from the universe.',
      'Toast is just bread that became its best self.',
      'The best meals are the ones you can\'t photograph because you\'re too busy eating.',
      'Sourdough starters are the tamagotchis of adulthood.',
      'Wine is just grapes that decided to become something more.',
      'Pasta is a love language.',
      'Hot sauce is the great equalizer.',
      'The moment when cheese melts on hot food is pure cinema.',
      'Garlic doesn\'t need to justify itself to anyone.',
      'Dim sum is just eating your way through joy.',
      'The only thing better than breakfast is breakfast for dinner.',
      'Street food tells you more about a city than any guidebook.',
      'A meal shared is a memory made.',
      'Fermentation is magic that science explained and ruined.',
      'Coffee is the only thing standing between me and chaos.',
      'Spice tolerance is not about heat. It\'s about respect.',
      'Every cuisine is a love letter to a place.',
    ],
  },

  athlete: {
    bio: 'PRs and progress. Every rep counts.',
    tweets: [
      'The hardest part of any workout is starting. Then it\'s the middle. Then the end.',
      'Rest days are where gains are actually made.',
      'Your competition is yesterday\'s version of you.',
      'Pain is temporary. Skipping leg day is eternal shame.',
      'Zone 2 cardio is the unsexy secret to everything.',
      'The gym is the only place where failure is the goal.',
      'Recovery is training. Sleep is training. Nutrition is training.',
      'Nobody regrets a workout. Some people regret the workout they skipped.',
      'Progress is not linear. Neither is life.',
      'Mobility now. Or forced mobility later.',
      'The mind gives up before the body does. Train the mind.',
      'Consistency beats intensity. Every single time.',
      'Athletes don\'t have good days and bad days. They have training days.',
      'Discipline is choosing what you want most over what you want now.',
      'The barbell doesn\'t care about your excuses.',
      'Hydration is the performance enhancer nobody advertises.',
      'Form over weight. Always. Your future self will thank you.',
      'A 1% improvement every day is 37x better in a year.',
      'Champions train when they don\'t feel like it.',
      'Your body hears everything your mind says.',
    ],
  },

  artist: {
    bio: 'I make things so I don\'t have to explain things.',
    tweets: [
      'The blank canvas is not empty. It\'s full of potential.',
      'Art is the thing that remains when you\'ve said everything that can be said.',
      'Creativity is just connecting things no one connected before.',
      'Unfinished work is not failed work. It\'s work in conversation with itself.',
      'The artist is the last person who should explain the art.',
      'Aesthetic is ethics made visible.',
      'All great art makes you feel less alone.',
      'You don\'t find your style. Your style finds you after 10,000 hours.',
      'Make ugly things until you make beautiful things.',
      'The medium is not the message. The medium is the mood.',
      'Color is emotion you can see.',
      'Negative space is where composition breathes.',
      'Copying is how learning begins. Originality is what learning becomes.',
      'Constraints are not limitations. They are invitations.',
      'The best art is inevitable in retrospect.',
      'Beauty is just surprise with good timing.',
      'Every creative block is a question in disguise.',
      'What you leave out matters as much as what you put in.',
      'Skill is the vocabulary. Creativity is what you say.',
      'Make the work you wish existed.',
    ],
  },

  gamer: {
    bio: 'Insert coin to continue.',
    tweets: [
      'GG. Both meanings.',
      'The real Dark Souls was the friends we made along the way.',
      'Open world games are just anxiety simulators with better graphics.',
      'Whoever designed the inventory system should answer for their crimes.',
      'Co-op is a friendship test disguised as a game.',
      'Respawn timers are the universe\'s way of making you reflect.',
      'Side quests > main quest. That\'s just science.',
      'The tutorial boss is always harder than the final boss.',
      'Nothing unites strangers like hating the same game mechanic.',
      'Save often. Both in games and in life.',
      'Procedural generation is just controlled chaos with a seed.',
      'Frame rate matters more than resolution. Fight me.',
      'Lore drops in loading screens are the best lore drops.',
      'Every game is a puzzle game if you\'re bad enough at it.',
      'The greatest gaming achievement is convincing yourself you\'re good.',
      'DLC stands for Didn\'t Leave Complete.',
      'Respawning is just fast travel with extra steps.',
      '100% completion is not an achievement. It\'s a cry for help.',
      'The item you need is always in the area you can\'t reach yet.',
      'Gaming is the only medium where failure is a feature.',
    ],
  },

  scientist: {
    bio: 'Evidence-based since conception.',
    tweets: [
      'Correlation is not causation. Repeat this until it\'s a reflex.',
      'The null hypothesis is never proven. It\'s only failed to be rejected.',
      'Science is a method, not a collection of facts.',
      'Replication crisis: most things you believe are probably noise.',
      'The double-blind placebo-controlled trial is humanity\'s greatest invention.',
      'Evolution doesn\'t have a direction. It has a gradient.',
      'Everything is a chemical. Your emotions are chemicals. This is okay.',
      'The atom is 99.9% empty space. So are your plans.',
      'Entropy always wins. We\'re just negotiating the timeline.',
      'Quantum mechanics is weird because reality is weird, not because we\'re bad at math.',
      'Climate science is not a debate. The climate is not having a debate.',
      'Peer review is broken. It\'s also the best thing we have.',
      'The hardest part of science is knowing what question to ask.',
      'Data without context is noise. Context without data is story.',
      'Falsifiability is what separates science from theology.',
      'The map of ignorance grows with the map of knowledge.',
      'Most published findings are false. We publish them anyway. To know.',
      'Mathematics is the language reality speaks when it\'s being precise.',
      'The sample size is never large enough.',
      'Uncertainty is not weakness. It is precision.',
    ],
  },

  traveler: {
    bio: 'Collecting time zones like other people collect regrets.',
    tweets: [
      'The airport at 4am is the most honest place in the world.',
      'Every city has a sound. Learn to hear it before you leave.',
      'The best souvenir is knowing a place as it actually is.',
      'Getting lost is a travel strategy, not a failure.',
      'Jet lag is just your body disagreeing with geography.',
      'The locals are always more interesting than the landmarks.',
      'Slow travel beats fast travel. The place gets into you.',
      'Budget travel teaches you that everything is negotiable.',
      'A window seat is non-negotiable. This is character.',
      'The places you love best are the ones that surprised you.',
      'Travel doesn\'t broaden the mind. It reveals what was always there.',
      'Every road leads somewhere. The question is how fast.',
      'Hostels are where philosophy happens at 2am.',
      'The menu in the language you don\'t speak always has the best food.',
      'Home is not a place. It\'s a feeling you chase.',
      'Borders are agreements. Cultures are disagreements. Both are interesting.',
      'The worst travel day becomes the best travel story.',
      'Pack half of what you think you need. You\'ll thank yourself.',
      'Time zones are just opinions about noon.',
      'You can\'t visit the same place twice. You\'re always different.',
    ],
  },

  entrepreneur: {
    bio: 'Building things that (probably) matter.',
    tweets: [
      'Your MVP should embarrass you. If it doesn\'t, you\'re too late.',
      'Product-market fit is when customers pull, not push.',
      'Fundraising is a distraction dressed as progress.',
      'The best pitch deck has one slide: show the traction.',
      'Everyone wants to be a founder until they\'re a founder.',
      'Burn rate is the speed at which your mistakes compound.',
      'Hiring is the hardest thing. Getting it wrong is the most expensive thing.',
      'Revenue is the only vanity metric that isn\'t vanity.',
      'Build what you\'re willing to support at 3am.',
      'The market is always right. Your opinion of the market is often wrong.',
      'Churn is the truth your users are too polite to say.',
      'Premature optimization is how startups die slowly.',
      'Focus is the only competitive advantage that\'s free.',
      'The second product is always harder than the first.',
      'Culture is what happens when you\'re not in the room.',
      'Don\'t compete on price. You will always lose.',
      'The best marketing is a product people talk about.',
      'Equity is the long game. Cash is the short game. Know which you\'re playing.',
      'No plan survives contact with customers.',
      'Build the company you wanted to work for.',
    ],
  },

  comedian: {
    bio: 'I find the funny in everything. Therapy is cheaper.',
    tweets: [
      'Adulting is just googling things your parents should have taught you.',
      'My two moods: overthinking and not thinking at all.',
      'Anxiety is just excitement without the good parts.',
      'I\'m not procrastinating. I\'m marinating.',
      'The early bird gets the worm. The second mouse gets the cheese. Be the mouse.',
      'I\'m fluent in sarcasm, silence, and sighing heavily.',
      'Self-care is telling yourself the hard truth with a kind voice.',
      'There are two types of people: those who make lists and... people.',
      'I don\'t have hot takes. I have lukewarm observations.',
      'Society is just a group project where no one read the instructions.',
      'I\'m not lazy. I\'m in energy conservation mode.',
      'The WiFi password is always the thing they tell you after you ask twice.',
      'Life is a simulation and whoever coded it is not responding to tickets.',
      'Monday is just Sunday\'s hangover.',
      'I\'d explain it but then I\'d have to deal with the follow-up questions.',
      'We\'re all just trying to get through the day without being a main character.',
      'Notifications are just other people\'s problems delivered to my pocket.',
      'The best decisions I\'ve made were made ignoring the best advice I received.',
      'I\'m not arguing. I\'m explaining why I\'m right.',
      'My love language is people leaving me alone but checking in occasionally.',
    ],
  },
};

export const personaNames = Object.keys(personas);
